# Chapter 2: Vectors Part 1

In [1]:
import numpy as np

## Creating and Visualizing Vector in NumPy

In [2]:
asList = [1,2,3]
asArray = np.array([1,2,3]) # 1D array
rowVec = np.array([ [1,2,3] ]) # Row vector
colVec = np.array([ [1], [2], [3]]) # Column vector

In [3]:
print(f'asList:  {np.shape(asList)}') # List
print(f'asArray: {asArray.shape}') # List
print(f'rowVec:  {rowVec.shape}') # 1 row x 3 col vector
print(f'colVec:  {colVec.shape}') # 3 row x 1 col vector

asList:  (3,)
asArray: (3,)
rowVec:  (1, 3)
colVec:  (3, 1)


## Operations on Vectors

### Adding Vectors

In [4]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6,9])

vPlusW = v + w
try:
    uPlusW = u + w # Error mismatched dimensions
except ValueError as err:
    print(err)

operands could not be broadcast together with shapes (4,) (3,) 


In [5]:
v = np.array([ [4,5,6] ]) # row vector
w = np.array([ [10,20,30] ]).T # column vector

print(f'v.shape: {v.shape}')
print(f'w.shape: {w.shape}')
print(v + w) # not expected results, v and w are broadcast, i.e expanded to matching shape

v.shape: (1, 3)
w.shape: (3, 1)
[[14 15 16]
 [24 25 26]
 [34 35 36]]


### Geometry of Vector Addition and Subtraction

### Scalar-Vector Multiplication

In [6]:
s = 2
a = [2,3,4] # list
b = np.array(a) # np array

print(s * a) # repeats list s times
print(s * b) # performs scalar-vector multiplication

[2, 3, 4, 2, 3, 4]
[4 6 8]


### Scalar-Vector Addition

In [7]:
s = 2
v = np.array([3,6])

print(s + v) # not defined in linear algebra, but works with numpy

[5 8]


### Geometry of Scalar-Vector Multiplication

### Transpose

In [8]:
v = np.array([ [1,2,3] ])
t = v.T

print(f'v: shape: {v.shape}\n{v}')
print(f't: shape: {t.shape}\n{t}')

v: shape: (1, 3)
[[1 2 3]]
t: shape: (3, 1)
[[1]
 [2]
 [3]]


### Vector Broadcasting in Python

In [9]:
v = np.array([ [1,2,3] ]).T # col vector
w = np.array([ [10,20] ])   # row vector

print(f'v.shape: {v.shape}')
print(f'w.shape: {w.shape}')
print(v + w) # addition with broadcasting

v.shape: (3, 1)
w.shape: (1, 2)
[[11 21]
 [12 22]
 [13 23]]


## Vector Magnitude and Unit Vectors 

In [10]:
v = np.array([ [1,2,3,7,8,9] ])
print(v)

v_dim = len(v) # number of dimensions of the array
print(v_dim)

v_mag = np.linalg.norm(v) # magnitude, i.e. length or norm
print(v_mag)

[[1 2 3 7 8 9]]
1
14.422205101855956


## Vector Dot Product (Inner Product)

In [11]:
v = np.array([ [1,2,3,4] ])
w = np.array([ [5,6,7,8] ])

try:
    np.dot(v, w) # not properly aligned, need row and column vector
except ValueError as err:
    print(err)

dot = np.dot(v, w.T) # first must be row, second must be column because dot is matrix multiplication
print(dot)        # matrix form
print(dot.item()) # scalar form

dot = np.vdot(v, w) # vdot can also be used, but only for vectors 
print(dot)

s = 10
scaled_dot = np.vdot(s * v, w) # scaling a vector, scales the dot product by the same amount
print(scaled_dot)

shapes (1,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)
[[70]]
70
70
700


### Dot Product is Distributive

In [12]:
# NOTE: these are arrays, not vectors, so transposing is not required when using dot below
a = np.array([ 0, 1, 2 ])
b = np.array([ 3, 5, 8 ])
c = np.array([ 13, 21, 34 ])

# dot product is distributive, a(b+c) == ab + ac
result_1 = np.dot(a, b+c)
result_2 = np.dot(a, b) + np.dot(a, c)

print(result_1, result_2, result_1 == result_2)

110 110 True


### Geometry of the Dot Product

## Other Vector Multiplications

### Hadamard Multiplication

In [13]:
a = np.array([ 5, 4, 8, 2 ])
b = np.array([ 1, 0, .5, -1])

print(a * b) # element-wise multiplication

[ 5.  0.  4. -2.]


### Outer Product

In [25]:
v = np.array([[1],[2],[3]]) # column vector
w = np.array([[10],[20]])   # column vector

print(v.shape)
print(w.shape)

print(np.outer(v, w)) # outer product

print(np.dot(v, w.T)) # outer product

try:
    print(np.dot(v, w))
except ValueError as err:
    print(err) # not aligned

try:
    print(np.dot(v.T, w)) # dot product
except ValueError as err:
    print(err) # not aligned


(3, 1)
(2, 1)
[[10 20]
 [20 40]
 [30 60]]
[[10 20]
 [20 40]
 [30 60]]
shapes (3,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)
shapes (1,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)


## Orthongonal Vector Decomposition