# Chapter 2: Vectors Part 1

In [1]:
import numpy as np

## Creating and Visualizing Vector in NumPy

In [2]:
asList = [1,2,3]
asArray = np.array([1,2,3]) # 1D array
rowVec = np.array([ [1,2,3] ]) # Row vector
colVec = np.array([ [1], [2], [3]]) # Column vector

In [3]:
print(f'asList:  {np.shape(asList)}') # List
print(f'asArray: {asArray.shape}') # List
print(f'rowVec:  {rowVec.shape}') # 1 row x 3 col vector
print(f'colVec:  {colVec.shape}') # 3 row x 1 col vector

asList:  (3,)
asArray: (3,)
rowVec:  (1, 3)
colVec:  (3, 1)


## Operations on Vectors

### Adding Vectors

In [11]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6,9])

vPlusW = v + w
uPlusW = u + w # Error mismatched dimensions

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [12]:
v = np.array([ [4,5,6] ]) # row vector
w = np.array([ [10,20,30] ]).T # column vector

print(f'v.shape: {v.shape}')
print(f'w.shape: {w.shape}')
print(v + w) # not expected results, v and w are broadcast, i.e expanded to matching shape

v.shape: (1, 3)
w.shape: (3, 1)
[[14 15 16]
 [24 25 26]
 [34 35 36]]


### Geometry of Vector Addition and Subtraction

### Scalar-Vector Multiplication

In [14]:
s = 2
a = [2,3,4] # list
b = np.array(a) # np array

print(s * a) # repeats list s times
print(s * b) # performs scalar-vector multiplication

[2, 3, 4, 2, 3, 4]
[4 6 8]


### Scalar-Vector Addition

In [16]:
s = 2
v = np.array([3,6])

print(s + v) # not defined in linear algebra, but works with numpy

[5 8]
